services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "${PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/usr/src/semesterly/data
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=${TIMEZONE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
