info:
  contact: {}
paths:
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Проверяет, работает ли сервер и есть ли подключение к базе данных
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Проверка подключения
      tags:
      - Hello
swagger: "2.0"
