basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API для управления расписанием учебных занятий
  title: Автоматизированная система по ведению расписания учебных занятий
  version: "1.0"
paths:
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Проверяет, работает ли сервер и есть ли подключение к базе данных
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Проверка подключения
      tags:
      - Hello
  /api/v1/insert-data:
    post:
      consumes:
      - application/json
      description: Вставляет данные расписания и экзаменов в базу данных
      produces:
      - application/json
      responses:
        "200":
          description: 'message: Data inserted successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'errors: [error messages]'
          schema:
            additionalProperties: true
            type: object
      summary: Вставка данных
      tags:
      - InsertData
  /api/v1/write-schedule:
    post:
      consumes:
      - application/json
      description: Сохраняет данные расписания в CSV файл
      produces:
      - application/json
      responses:
        "200":
          description: 'message: Schedule written to file successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error: Failed to fetch schedule items" "error: Failed to write
            schedule to file'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сохранение расписания
      tags:
      - WriteSchedule
swagger: "2.0"
